### Creating Tensors - Just like numpy arrays

In [5]:
import numpy as np

In [6]:
arr = [[1,2],[3,4]]
arr

[[1, 2], [3, 4]]

In [9]:
x = np.array(arr)

print(x.shape)
print(x.size)

(2, 2)
4


In [1]:
import torch

In [12]:
y = torch.tensor(arr)
y

tensor([[1, 2],
        [3, 4]])

In [13]:
type(y)

torch.Tensor

### Create Matrices with default values

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
np.random.rand(2,2)

array([[0.11315252, 0.35741053],
       [0.14157068, 0.35468799]])

In [20]:
torch.rand(2,2)

tensor([[0.8177, 0.4354],
        [0.1917, 0.1209]])

### Seeds for replicatiability

In [22]:
np.random.seed(11)
np.random.rand(2,2)

array([[0.18026969, 0.01947524],
       [0.46321853, 0.72493393]])

In [23]:
torch.manual_seed(11)
torch.rand(2,2)

tensor([[0.1490, 0.4866],
        [0.9857, 0.1684]])

### Seed for GPU

In [28]:
torch.cuda.is_available() 


False

### Numpy and Torch bridge

In [31]:
np_array = np.ones((2,2))
print(np_array)
print()
print(type(np_array))

[[1. 1.]
 [1. 1.]]

<class 'numpy.ndarray'>


In [34]:
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
print()
print(type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

<class 'torch.Tensor'>


In [36]:
np_array_new = np.ones((2,2) , dtype=np.int8)
print(np_array_new)
print()
print(type(np_array_new))

[[1 1]
 [1 1]]

<class 'numpy.ndarray'>


In [37]:
torch_tensor_new = torch.from_numpy(np_array_new)
print(torch_tensor_new)
print()
print(type(torch_tensor_new))

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

<class 'torch.Tensor'>


### Torch to Numpy

In [39]:
torch_tensor = torch.ones(2,2)
torch_tensor

tensor([[1., 1.],
        [1., 1.]])

In [40]:
type(torch_tensor)

torch.Tensor

In [43]:
torch_to_numpy = torch_tensor.numpy()
torch_to_numpy

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [44]:
type(torch_to_numpy)

numpy.ndarray

### Tensor Operations

##### Reizing Tensors

In [48]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [49]:
a.size()

torch.Size([2, 2])

In [50]:
a.view(4)

tensor([1., 1., 1., 1.])

In [52]:
a.view(4).size()

torch.Size([4])

#### Element wise addition

In [54]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [55]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [56]:
c = a + b
c

tensor([[2., 2.],
        [2., 2.]])

In [57]:
c = torch.add(a,b)
c

tensor([[2., 2.],
        [2., 2.]])

#### Tensor Mean

In [67]:
a = torch.tensor([1,2,3,4,5,6,7,8,9,10])
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a.size()

torch.Size([10])

In [70]:
a.float().mean() # or a.mean(dim=0)

tensor(5.5000)

#### Standard deviation

In [74]:
a.float().std()

tensor(3.0277)