## Variables and Gradients

### Variable

In [2]:
import torch
from torch.autograd import Variable

In [4]:
a = Variable(torch.ones(2,2) , requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
b = Variable(torch.ones(2,2) , requires_grad=True)
b

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
a + b

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [7]:
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [8]:
a * b

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

In [9]:
torch.mul(a,b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

### Gradient

In [21]:
#x = Variable(torch.tensor(5.0) , requires_grad=True)
x = Variable(torch.ones(2) , requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [22]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [23]:
o = 1/2 * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [25]:
o.backward()

In [27]:
x.grad

tensor([10., 10.])