# Doing More Numpy - Basic Array Operations

In [2]:
import numpy as np
import pandas as pd
import os

In [5]:
df = pd.read_csv('data/revenue_pdt_qtr.csv')
df

Product QTR  Revenue
0        A  Q1     4500
1        A  Q2     5000
2        A  Q3     6000
3        A  Q4     5500
4        B  Q1     3600
5        B  Q2     4400
6        B  Q3     4800
7        B  Q4     4800
8        C  Q1     6000
9        C  Q2     9000
10       C  Q3    12000
11       C  Q4    13500
12       D  Q1     3000
13       D  Q2     6000
14       D  Q3     9000
15       D  Q4     6000
16       E  Q1     2222
17       E  Q2     4444
18       E  Q3     6666
19       E  Q4     8888

In [8]:
# revenue into 2d array - of the shape 5 rows and 4 columns representing 5 products and 4 quarters
revenue = df['Revenue'].to_numpy().reshape(5,4)
revenue

array([[ 4500,  5000,  6000,  5500],
       [ 3600,  4400,  4800,  4800],
       [ 6000,  9000, 12000, 13500],
       [ 3000,  6000,  9000,  6000],
       [ 2222,  4444,  6666,  8888]])

In [30]:
# Total annual revenue for store - sum of all the revenue
#sum(sum(revenue))
#np.sum(revenue)
#revenue.sum()
revenue.sum(axis = None)

125320

In [27]:
# Total annual revenue for each product - sum of each of the rows - axis 1
# np.sum(revenue,axis = 1)
revenue.sum(axis=1)

array([21000, 17600, 40500, 24000, 22220])

In [29]:
# Total annual revenue for each quarter - sum of each of the columns - axis 0
#np.sum(revenue , axis = 0)
revenue.sum(axis = 0)

array([19322, 28844, 38466, 38688])

In [49]:
# Minumum revenue for each quarter - min value in each column - axis 0
#np.min(revenue , axis = 0)
#revenue.min(axis = 0)
#np.argmin(revenue,axis=0)
revenue.min(0)

array([2222, 4400, 4800, 4800])

In [50]:
# Minimum revenue for each product - min value in each row - axis 1
#np.min(revenue , axis = 1)
#revenue.min(axis = 1)
#np.argmin(revenue , axis = 1)
revenue.min(1)

array([4500, 3600, 6000, 3000, 2222])

In [55]:
# for each product , the quarter of min value - index of min value each row , for each products , axis 1
#np.argmin(revenue , axis = 1)
np.argmin(revenue , 1)

array([0, 0, 0, 0, 0])

In [56]:
# for each quarter , product with min value - index of min value each column , for each quarter , axis 0 
#np.argmin(revenue , axis = 0)
np.argmin(revenue , 0)

array([4, 1, 1, 1])

In [67]:
# for each quarter , when revenue > 5000 - axxis = 0
#revenue > 5000
#so in quarter 1 , only 1 product with revenue > 5000
(revenue > 5000).sum(0)

array([1, 2, 4, 4])

In [68]:
# for each product , when revenue > 5000 - axis = 1
#so first product , only 2 quarters with revenue > 5000 but no quarters > 5000 for product 1
(revenue > 5000).sum(1)

array([2, 0, 4, 3, 2])