# Doing More Numpy - Numpy Arrays

## Array Basic

In [3]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.arange(4,8)

array([4, 5, 6, 7])

In [8]:
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
np.random.randint(20,26) # starting and endoing

24

In [27]:
np.random.randint(1,26,5) # 5 is number of random int between 1 and 25 , 26 is exclusive

array([21,  3, 21, 10,  9])

In [30]:
np.random.randint(1,126,(3,5)) # 3 , 5 is the shape of the array , 3 rows 5 columns

array([[  7,  80, 107, 115,  74],
       [ 56,  46, 115,   5,  55],
       [ 48,  84,  62, 119,  56]])

In [32]:
np.random.randint(1,126,(2,3,5)) # 3 dimensional array

array([[[  1, 103,  85, 102,   1],
        [ 96,  61,  73, 101,  14],
        [121,  66, 109,  78,  39]],

       [[ 84,  77,  17,  23,  85],
        [ 94,  75,   6,  91,  19],
        [ 93,  27, 108,  21,  93]]])

In [33]:
np.random.randint(1,126,(2,3,5)).size

30

In [34]:
np.random.randint(1,126,(2,3,5)).shape

(2, 3, 5)

In [35]:
np.random.randint(1,126,(2,3,5)).ndim

3

In [36]:
np.random.randint(1,126,(2,3,5)).dtype

dtype('int64')