# Doing More Numpy - Array Indexing and Slicing

### axis 0 - vertical
### axis 1 - horizontal

### For 3 dimensions , 3 axis

In [8]:
import numpy as np
import pandas as pd
import os

In [12]:
df = pd.read_csv('data/sales_pdt_qtr_v2.csv')

In [13]:
sales = df['Sales'].to_numpy()

In [14]:
sales

array([ 450,  500,  600,  550,   45,   55,   60,   60, 4000, 6000, 8000,
       9000,   10,   20,   30,   20, 1111, 2222, 3333, 4444])

In [16]:
sales.shape

(20,)

In [22]:
sales = sales.reshape(5,-1) # 5,4 or 5,-1 or -1,4 

### 1D array

In [23]:
sales

array([[ 450,  500,  600,  550],
       [  45,   55,   60,   60],
       [4000, 6000, 8000, 9000],
       [  10,   20,   30,   20],
       [1111, 2222, 3333, 4444]])

In [21]:
sales[0] # first row 

array([450, 500, 600, 550])

In [24]:
sales[2:] #row 3 to end 

array([[4000, 6000, 8000, 9000],
       [  10,   20,   30,   20],
       [1111, 2222, 3333, 4444]])

In [25]:
sales[[0,2,3]]

array([[ 450,  500,  600,  550],
       [4000, 6000, 8000, 9000],
       [  10,   20,   30,   20]])

### 2D array

In [26]:
sales

array([[ 450,  500,  600,  550],
       [  45,   55,   60,   60],
       [4000, 6000, 8000, 9000],
       [  10,   20,   30,   20],
       [1111, 2222, 3333, 4444]])

In [27]:
sales[:,0] #the first column , all the rows since :

array([ 450,   45, 4000,   10, 1111])

In [28]:
sales[:,0:3] #first 3 columns , all the rows since :

array([[ 450,  500,  600],
       [  45,   55,   60],
       [4000, 6000, 8000],
       [  10,   20,   30],
       [1111, 2222, 3333]])

In [29]:
sales[:,[1,3]] # 2nd and 4th columns , all the rows since :

array([[ 500,  550],
       [  55,   60],
       [6000, 9000],
       [  20,   20],
       [2222, 4444]])

In [30]:
sales[1,3]

60

In [31]:
sales[0:3,2:]

array([[ 600,  550],
       [  60,   60],
       [8000, 9000]])

In [36]:
# error - sales[[0,2,4],[0,3]]
sales[[0,2,4]][:,[0,3]] #slicing twice ....

array([[ 450,  550],
       [4000, 9000],
       [1111, 4444]])

In [37]:
sales[[0,4],[0,3]] # 0,0 and 4,3

array([ 450, 4444])

In [41]:
sales[1:4,[0,1,3]]

array([[  45,   55,   60],
       [4000, 6000, 9000],
       [  10,   20,   20]])