# Doing More Numpy - Numpy Arrays

## Reshaping 1 dimensional arrays to higher dimensions

In [2]:
import numpy as np

In [5]:
a = np.arange(1,13)

In [7]:
a.shape

(12,)

In [10]:
a.shape=(3,4) #a is now 3 by 4 2 D array. 3 rows and 4 columns. See below , reshape doesn't change the original array.

In [12]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
b = np.arange(1,13)

In [14]:
b.reshape(3,4) #same as shape ? No. b is unchanged but a was changed by shape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
c = a.reshape(2,6)

In [17]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
c = a.reshape(2,2,3) # must get 12 elements as in original array
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Reshaping with -1  , unknown dimension

In [22]:
a = np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
a.reshape(-1,3) # must have 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [26]:
a.reshape(-1,6) # must have 6 columns

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [27]:
a.reshape(3,-1) # must have 3 rows

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [28]:
a.reshape(-1,4) # must have 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [29]:
a.reshape(-1,2) # must have 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [30]:
a.reshape(2,3,-1) # 2d - must have 2 inner arrays of 3 rows and unknown columns

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [33]:
a.reshape(4,3,-1) # 2d -  must have 4 inner arrays of 3 rows and unknown columns 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [34]:
A = np.random.randint(100,size=(4,5))
A

array([[77, 30, 92, 79, 33],
       [27, 38, 41, 87, 73],
       [91, 57, 45, 45, 87],
       [26, 62, 18, 33, 43]])

In [35]:
A = np.arange(1,73)
print(A.reshape(2,2,-1).shape)
print(A.reshape(3,4,-1).shape)
print(A.reshape(4,6,-1).shape)

(2, 2, 18)
(3, 4, 6)
(4, 6, 3)
