# Doing More with Numpy - List vs Numpy Arrays

### 1 Dimension Array

In [6]:
# Data - 1d

import numpy as np

L = [85,71,68,92,79]
A = np.array([85,71,68,92,79])

In [7]:
print(L)
print(A)

[85, 71, 68, 92, 79]
[85 71 68 92 79]
[1, 2, 3]


In [9]:
# Add 5 grace marks to students
# using list comprehension
[i+5 for i in L]

[90, 76, 73, 97, 84]

In [10]:
# using numpy array
A + 5

array([90, 76, 73, 97, 84])

### 2 Dimensions Array

### The table of students' scores in 3 subjects

| Subject 1 | Subject 2 | Subject 3 |
| :---------| :-------- : | ---------|
|    68     |      84    |    63    |
|    99     |      83    |    75    |
|    70     |      90    |    94    |
|    62     |      94    |    74    |
|    94     |      84    |    75    |

In [11]:
# data - 2d
L = [[68,84,63],[99,83,75],[70,90,94],[62,94,74],[94,84,75]]
A = np.array([[68,84,63],[99,83,75],[70,90,94],[62,94,74],[94,84,75]])

In [13]:
print(L)
print(A)

[[68, 84, 63], [99, 83, 75], [70, 90, 94], [62, 94, 74], [94, 84, 75]]
[[68 84 63]
 [99 83 75]
 [70 90 94]
 [62 94 74]
 [94 84 75]]


In [17]:
# only get scores in subject 1 - 1st column
# in list
[i[0] for i in L]

[68, 99, 70, 62, 94]

In [19]:
#in np array
# all the rows - : , but only 1st column 0 -
A[:,0]

array([68, 99, 70, 62, 94])

In [22]:
# max score of each student - each row
#using list
[max(i) for i in L]

[84, 99, 94, 94, 94]

In [26]:
#using np array
#axis 1 , horizontal - meaning each row
np.max(A , axis = 1)

array([84, 99, 94, 94, 94])

In [29]:
# can also use the max from Array A directly
# 1 is the axis value , 0 or 1
A.max(1)

array([84, 99, 94, 94, 94])

In [33]:
# Get top score in each subject - each column
# using list
[max(i[j] for i in L) for j in range(3)]

[99, 94, 94]

In [36]:
# using np array
# axis 0 means vertical - by column
np.max(A , axis = 0)

array([99, 94, 94])

In [35]:
A.max(0)

array([99, 94, 94])