# numpy arrays as data containers 
### The 2 csv files are in data folder

In [4]:
import numpy as np
import pandas as pd
import os

In [7]:
os.chdir('/home/rocky')
os.getcwd()

'/home/rocky'

In [15]:
df = pd.read_csv('data/sales_pdt_qtr_v1.csv')
df

Product QTR  Sales
0        A  Q1    450
1        A  Q2    500
2        A  Q3    600
3        A  Q4    550
4        B  Q1     45
5        B  Q2     55
6        B  Q3     60
7        B  Q4     60
8        C  Q1   4000
9        C  Q2   6000
10       C  Q3   8000
11       C  Q4   9000

In [16]:
sales=df['Sales'].to_numpy()
sales

array([ 450,  500,  600,  550,   45,   55,   60,   60, 4000, 6000, 8000,
       9000])

In [17]:
sales.reshape(3,4)

array([[ 450,  500,  600,  550],
       [  45,   55,   60,   60],
       [4000, 6000, 8000, 9000]])

In [18]:
df = pd.read_csv('data/sales_year_pdt_qtr_v1.csv')
df

Year Product QTR  Sales
0   2019       A  Q1    300
1   2019       A  Q2    350
2   2019       A  Q3    400
3   2019       A  Q4    500
4   2019       B  Q1     25
5   2019       B  Q2     30
6   2019       B  Q3     30
7   2019       B  Q4     40
8   2019       C  Q1   3000
9   2019       C  Q2   4000
10  2019       C  Q3   5000
11  2019       C  Q4   6000
12  2020       A  Q1    450
13  2020       A  Q2    500
14  2020       A  Q3    600
15  2020       A  Q4    550
16  2020       B  Q1     45
17  2020       B  Q2     55
18  2020       B  Q3     60
19  2020       B  Q4     60
20  2020       C  Q1   4000
21  2020       C  Q2   6000
22  2020       C  Q3   8000
23  2020       C  Q4   9000

In [19]:
sales=df['Sales'].to_numpy()
sales

array([ 300,  350,  400,  500,   25,   30,   30,   40, 3000, 4000, 5000,
       6000,  450,  500,  600,  550,   45,   55,   60,   60, 4000, 6000,
       8000, 9000])

In [20]:
sales.reshape(2,3,4)

array([[[ 300,  350,  400,  500],
        [  25,   30,   30,   40],
        [3000, 4000, 5000, 6000]],

       [[ 450,  500,  600,  550],
        [  45,   55,   60,   60],
        [4000, 6000, 8000, 9000]]])