# Lazy Programmer - Generating Data in Numpy

In [2]:
import numpy as np

In [3]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [7]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [8]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random((2,3))

array([[0.78610306, 0.14275669, 0.77371763],
       [0.5579217 , 0.30167293, 0.02045839]])

In [14]:
# random numbers from normal distribution
# meaning mean is 0 and standard deviation is 1
np.random.randn(2,3)

array([[-1.27672234,  0.11964812, -0.54165641],
       [-0.48781901,  1.68305221,  0.53968503]])

In [15]:
R = np.random.randn(10000)

In [17]:
R.mean()

0.011152503440403024

In [18]:
R.std()

1.00411090790335

In [19]:
R.var()

1.0082387153704897

In [20]:
np.mean(R)

0.011152503440403024

In [21]:
R = np.random.randn(10000 , 3)

In [22]:
R.mean(axis=0)

array([-0.01603303, -0.00164902,  0.01221186])

In [23]:
R.mean(axis=1)

array([-0.83582984, -0.0119597 ,  0.02367705, ..., -0.48352321,
        1.00474925,  0.73546888])

In [25]:
R.mean(axis=1).shape

(10000,)

In [26]:
np.cov(R)

array([[ 0.12631518, -0.38501333,  0.18769218, ...,  0.0315196 ,
        -0.11524242,  0.12320318],
       [-0.38501333,  2.96193449, -0.45684676, ..., -1.16197167,
         0.28060748,  1.83088113],
       [ 0.18769218, -0.45684676,  0.28631901, ..., -0.02185229,
        -0.17579222,  0.3252508 ],
       ...,
       [ 0.0315196 , -1.16197167, -0.02185229, ...,  0.6431483 ,
         0.01335468, -1.2842922 ],
       [-0.11524242,  0.28060748, -0.17579222, ...,  0.01335468,
         0.10793174, -0.19957347],
       [ 0.12320318,  1.83088113,  0.3252508 , ..., -1.2842922 ,
        -0.19957347,  2.8422889 ]])

In [27]:
np.cov(R.T) #transpose

array([[ 1.01716023,  0.00428838,  0.0089717 ],
       [ 0.00428838,  1.00972905, -0.00488226],
       [ 0.0089717 , -0.00488226,  1.02927899]])

In [30]:
np.random.randint( 0 , 10 , size = (3,3))

array([[1, 0, 5],
       [3, 0, 4],
       [9, 8, 5]])

In [33]:
np.random.choice(10 , size = (3,3))

array([[5, 4, 3],
       [8, 5, 4],
       [5, 4, 5]])