# Lazy Programmer - Nupy Matrices

In [2]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [5]:
L[0]

[1, 2]

In [6]:
L[0][1]

2

In [10]:
import numpy as np

In [12]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [13]:
A[0][1]

2

In [14]:
A[0,1]

2

In [15]:
A[:,0]

array([1, 3])

In [16]:
A.T

array([[1, 3],
       [2, 4]])

In [17]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [18]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [20]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [25]:
np.diag(A)

array([1, 4])

In [26]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [27]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))