# Lazy Programmer - Numpy Stack

In [2]:
import numpy as np

In [3]:
L = [1,2,3]

In [4]:
A = np.array([1,2,3])

In [5]:
for e in L:
    print(e)

1
2
3


In [6]:
for e in A:
    print(e)

1
2
3


In [7]:
L.append(4)
L

[1, 2, 3, 4]

In [8]:
A.append(4)
A

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L + [5] #adding 2 lists or same as appending a list to the end of the list

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4]) #broadcasting

array([5, 6, 7])

In [11]:
A

array([1, 2, 3])

In [12]:
2 * A

array([2, 4, 6])

In [13]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L2 = []
for e in L:
    L2.append(e + 3)
    
L2

[4, 5, 6, 7]

In [19]:
L2 = [i + 3 for i in L]
L2

[4, 5, 6, 7]

In [23]:
L2 = []
for e in L :
    L2.append(e**2)

L2

[1, 4, 9, 16]

In [24]:
A ** 2

array([1, 4, 9])

In [25]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])