# Lazy Programmer - Numpy Linear Systems

In [2]:
import numpy as np

In [11]:
# Total of 2200 Children and Adults paid $5050. $1.5 / Children and $4 / Adult.
# How many children and adult ?

In [ ]:
# C + A = 2200
# 1.5C + 4A = 5050

In [5]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

In [6]:
np.linalg.solve(A,b)

array([1500.,  700.])

In [7]:
# bad way to solve
np.linalg.inv(A).dot(b)

array([1500.,  700.])

In [8]:
# Suppose, a fruit-seller sold 20 mangoes and 10 oranges in one day for a total of $350. The next day he sold 17 mangoes and 22 oranges for $500. 
# If the prices of the fruits remained unchanged on both the days, what was the price of one mango and one orange?

In [9]:
# 20x + 10y = 350
# 17x + 22y = 500

In [15]:
A = np.array([[20,10],[17,22]])
b = np.array([350,500])
np.linalg.solve(A,b)

array([10., 15.])

In [12]:
# 2B = A
# 3B - 10 = A

In [18]:
A = np.array([[2,0],[3,-10]])
B = np.array([1,1])
np.linalg.solve(A,B)

array([0.5 , 0.05])