## Numpy Indexing

In [9]:
import numpy as np

x = np.array([[82,25,91],[46,-4,-56],[75,-5,14],[34,57,88]])
x

array([[ 82,  25,  91],
       [ 46,  -4, -56],
       [ 75,  -5,  14],
       [ 34,  57,  88]])

In [7]:
print(x.shape)
print(x.ndim)
print(x.size)
#x.reshape
#n.arange()
#np.eye()
#np.full()
#x.random.random(())
#x.random.randint(())
#np.zeros()
#np.ones()

(4, 3)
2
12


In [10]:
x[2,1]

-5

In [13]:
x[:,1] # 2nd column
x[:,1].reshape(4,1) #2nd column reshaped to 4 rows 1 column 

array([[25],
       [-4],
       [-5],
       [57]])

In [15]:
x[1,:] #2nd row

array([ 46,  -4, -56])

In [16]:
x

array([[ 82,  25,  91],
       [ 46,  -4, -56],
       [ 75,  -5,  14],
       [ 34,  57,  88]])

In [24]:
x[[0,3,1],[1,2,1]] #1st row 2nd column , 4th row , 3rd column , 2nd row 2nd column

array([25, 88, -4])

In [26]:
#x[2,1] #-5
x[2,1] = 77 #change to 77
x

array([[ 82,  25,  91],
       [ 46,  -4, -56],
       [ 75,  77,  14],
       [ 34,  57,  88]])

In [27]:
x[:,1] = [75,141,220,500] #change 2nd column to these values
x

array([[ 82,  75,  91],
       [ 46, 141, -56],
       [ 75, 220,  14],
       [ 34, 500,  88]])

In [31]:
#this is what is called numpy broadcasting. broadcasting refers to a particular value getting reflected to multiple elements in numpy 
# set all the values in 2nd column to 300
x[:,1] = 300 
x

array([[ 82, 300,  91],
       [ 46, 300, -56],
       [ 75, 300,  14],
       [ 34, 300,  88]])

In [34]:
x[[0,3,1],[1,2,1]] = [49,64,81]
x

array([[ 82,  49,  91],
       [ 46,  81, -56],
       [ 75, 300,  14],
       [ 34, 300,  64]])

### Boolean Indexing

In [4]:
import numpy as np

x = np.array([[82,25,91],[46,-4,-56],[75,-5,14],[34,57,88]])
x

array([[ 82,  25,  91],
       [ 46,  -4, -56],
       [ 75,  -5,  14],
       [ 34,  57,  88]])

In [28]:
x[x%2 == 0]

array([ 82,  46,  -4, -56,  14,  34,  88])

In [38]:
y = np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.where(np.array(y)==1)

(array([0, 1, 2]), array([0, 1, 2]))

In [36]:
zip(*np.where(np.array(y)==1))

In [56]:
#x[0] #1st row
#x[:,0] #1st column
x[2] > 12 #which number in the 3rd row more than 12 ?
sum(x[2]) > 200 #is the sum of the values in 3rd row more than 200?
x[2] + 1 #add 1 to the values in the 3rd row

array([76, -4, 15])

In [71]:
x[:,1] >=25 #true or false of the rows that have the 2nd column values that are greater than equal to 25
#x[x[:,1] >= 25,:] #rows that have the 2nd column that are greater than equal to 25

array([ True, False, False,  True])

In [76]:
(x[:,1] >=25) | (x[:,2] <= 0) # OR
(x[:,1] >=25) & (x[:,2] <= 0) # AND

array([False, False, False, False])

## View vs Copy

In [79]:
orig = np.array([[30,25,12],[21,-5,8],[75,14,100],[50,92,700]])
print("orig")
print(orig)
y = orig #y is a not a copy but pointer to the orig
y[0,2] = -11111 #change 1st row , 3rd column to -11111
print("orig after modification")
print(orig)

orig
[[ 30  25  12]
 [ 21  -5   8]
 [ 75  14 100]
 [ 50  92 700]]
orig after modification
[[    30     25 -11111]
 [    21     -5      8]
 [    75     14    100]
 [    50     92    700]]


In [83]:
orig = np.array([[30,25,12],[21,-5,8],[75,14,100],[50,92,700]])
print("orig")
print(orig)
new = orig[1:3] # get 2nd row and 3rd row from orig and assign to a new variable
print('new')
print(new)

orig
[[ 30  25  12]
 [ 21  -5   8]
 [ 75  14 100]
 [ 50  92 700]]
new
[[ 21  -5   8]
 [ 75  14 100]]


In [85]:
new[1,2] = 5000
print('new after modification')
print(new)
print('orig')
print(orig)

new after modification
[[    21 -11111      8]
 [    75     14   5000]]
orig
[[    30     25     12]
 [    21 -11111      8]
 [    75     14   5000]
 [    50     92    700]]


In [86]:
orig = np.array([[30,25,12],[21,-5,8],[75,14,100],[50,92,700]])
print("orig")
print(orig)
new = orig[1:3].copy() #this time new is not pointing to the orig since it is copied
new[1,2] = 5000 #no changes to the orig
print('new after modification')
print(new)
print('orig')
print(orig)

orig
[[ 30  25  12]
 [ 21  -5   8]
 [ 75  14 100]
 [ 50  92 700]]
new after modification
[[  21   -5    8]
 [  75   14 5000]]
orig
[[ 30  25  12]
 [ 21  -5   8]
 [ 75  14 100]
 [ 50  92 700]]


In [88]:
orig = np.array([[30,25,12],[21,-5,8],[75,14,100],[50,92,700]])
new = orig[[0,3,1],[2,0,1]] #same as copy ?
print('new')
print(new)

new
[12 50 -5]


In [89]:
new[2] = 5000
print()
print(new)
print()
print('original after modification')
print(orig)



[  12   50 5000]

original after modification
[[ 30  25  12]
 [ 21  -5   8]
 [ 75  14 100]
 [ 50  92 700]]


In [91]:
orig = np.array([[30,25,12],[21,-5,8],[75,14,100],[50,92,700]])
new = orig[orig[:,1]>=25] #check all the rows and 2nd column and return the result,row i=if 2nd column is more than or equal to 25 
#above is also a copy
print()
print(new)


[[ 30  25  12]
 [ 50  92 700]]


In [92]:
new[1,2] = 5000
print()
print(new)
print()
print('original after modification')
print(orig)


[[  30   25   12]
 [  50   92 5000]]

original after modification
[[ 30  25  12]
 [ 21  -5   8]
 [ 75  14 100]
 [ 50  92 700]]


In [93]:
#change the original directly
orig[orig[:,1]>=25] += 100
print(orig)

[[130 125 112]
 [ 21  -5   8]
 [ 75  14 100]
 [150 192 800]]
