## Numpy Array Creation

In [2]:
import numpy as np

a = np.array([7,52,3,8,10])
a

array([ 7, 52,  3,  8, 10])

In [6]:
a = np.array([7,'my data',3,8,10])
a

array(['7', 'my data', '3', '8', '10'], dtype='<U21')

In [7]:
x = np.array([[34,5,6],[-5,21,67],[77,92,-6],[33,61,84]])
x

array([[34,  5,  6],
       [-5, 21, 67],
       [77, 92, -6],
       [33, 61, 84]])

In [9]:
x.shape #rows , columns

(4, 3)

In [11]:
x.shape[0] #shape of rows

4

In [13]:
x.shape[1] #shape of columns

3

In [20]:
x[1][2] #2nd row , 3rd column

67

In [23]:
x.size #4 rows , 3 columns. 4 x 3 = 12

12

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.full((3,4),"Hello") #3 rows and 4 columns of "Hello"

array([['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello']], dtype='<U5')

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.arange(4)

array([0, 1, 2, 3])

In [39]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [43]:
np.arange(3,15).reshape(4,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
np.tile(np.arange(4),(3,1)) # 0 - 3 list , 3 rows and repeat 1 time in column

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [45]:
np.tile(np.arange(4),(3,2)) # 0 - 3 list , 3 rows and repeat 2 time in column

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [46]:
np.tile(np.array([31,-4,7,59]),(3,1)) #given np array repeated in 3 rows and 1 time in column 

array([[31, -4,  7, 59],
       [31, -4,  7, 59],
       [31, -4,  7, 59]])

In [47]:
np.tile(np.array([31,-4,7,59]),(3,2)) #given np array repeated in 3 rows and 2 time in column 

array([[31, -4,  7, 59, 31, -4,  7, 59],
       [31, -4,  7, 59, 31, -4,  7, 59],
       [31, -4,  7, 59, 31, -4,  7, 59]])

In [49]:
np.tile(np.array([[31,-4,7,59],[45,-8,21,6]]),(3,2)) #given 2 dim np array repeated in 3 rows and 2 time in column 

array([[31, -4,  7, 59, 31, -4,  7, 59],
       [45, -8, 21,  6, 45, -8, 21,  6],
       [31, -4,  7, 59, 31, -4,  7, 59],
       [45, -8, 21,  6, 45, -8, 21,  6],
       [31, -4,  7, 59, 31, -4,  7, 59],
       [45, -8, 21,  6, 45, -8, 21,  6]])

In [58]:
np.random.random((3,4))

array([[0.79407142, 0.44149236, 0.22614252, 0.41987745],
       [0.80314815, 0.90270028, 0.33158608, 0.23454522],
       [0.18595533, 0.18077908, 0.72820878, 0.63017934]])

In [67]:
74 * np.random.random((3,4)) + 6 #random number between 6-80 in 3 rows 4 columns

array([[65.36056598, 64.48368242, 18.97404658, 27.51549429],
       [67.7252848 , 47.46106628, 77.90627316, 65.60321308],
       [75.6548738 , 70.20015391,  7.75347443, 15.60389205]])

In [77]:
np.random.seed(2) #so that no changes to the random number below , for dev/testing
np.random.random((3,4))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209]])

In [115]:
#np.random.seed(55)
a = np.array([3,-5,67,88,2,15,39,57])
np.random.choice(a,5,replace=False) #take 5 numbers out of the np array. no replacement. so the number selected in removed from the pool for selection.

array([88, 39,  2,  3, 15])

In [119]:
a = np.array([3,-5,67,88,2,15,39,57])
np.random.choice(a,5,replace=True) #take 5 numbers out of the np array. with replacement , the number can be selected multiple times ... basic prob

array([67, 15, 15, 39,  2])

In [153]:
np.random.randint(low = 6 , high = 80 , size=(3,4))

array([[ 7, 13, 11, 54],
       [74, 21, 14, 14],
       [20, 63, 30,  8]])