# Numpy Statistical Functions

In [2]:
import numpy as np

In [3]:
y = np.array([6,12,8,4,15,52,7])

In [5]:
np.sum(y) # or y.sum as below

104

In [9]:
y.sum()

104

In [10]:
np.min(y)

4

In [11]:
np.max(y)

52

In [13]:
y.max()

52

In [15]:
y.min()

4

In [17]:
l1 = [23,45,77]
np.sum(l1)

145

In [18]:
l1.sum() #this won't work

AttributeError: 'list' object has no attribute 'sum'

In [20]:
y

array([ 6, 12,  8,  4, 15, 52,  7])

### Get the index of min , max and sorted np array

In [25]:
print(np.argmin(y)) 
print(np.argmax(y))
print(np.argsort(y))

3
5
[3 0 6 2 1 4 5]


In [28]:
print(y[np.argmin(y)])
print(np.min(y))
print(y.min())

4
4
4


In [31]:
x = np.array([[20,1,18,26],[12,7,22,9],[25,31,16,14]])
print(x)

[[20  1 18 26]
 [12  7 22  9]
 [25 31 16 14]]


### Axis = 0 --->  collapses rows into a single aggregate row.

### Axis = 1 ----> collapses columns into a single aggregate column.

In [35]:
np.sum(x, axis = 0) # 3 rows become 1 aggregate row

array([57, 39, 56, 49])

In [37]:
np.sum(x , axis = 1) # 4 columns become 1 aggregate column

array([65, 50, 86])

In [40]:
np.sum(x , axis = None) #total across all rows and all columns

201

In [42]:
np.sum(x) # default is axis = 0 

201

In [44]:
np.min(x , axis=0)

array([12,  1, 16,  9])

In [46]:
np.argmin(x , axis = 0 ) # return the index of min value in each row. 4 columns in total so list of 4.

array([1, 0, 2, 1])

In [47]:
np.argmin(x, axis = 1) # return the index of min value in each column. 3 rows in total so list of 3.

array([1, 1, 3])