# Numpy Arithmetic Operations / Broadcasting

In [3]:
import numpy as np

In [4]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [6]:
x + y

array([[ 6,  8],
       [10, 12]])

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
a = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
b = np.array([30,50,70])
print('a')
print(a)
print()
print('b')
print(b)
print()
print('a + b - broadcasting to rows - b is repeated 3 more times so it is now 4 rows , same as a')
a + b



a
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]

b
[30 50 70]

a + b - broadcasting to rows - b is repeated 3 more times so it is now 4 rows , same as a


array([[31, 51, 71],
       [32, 52, 72],
       [33, 53, 73],
       [34, 54, 74]])

In [18]:
a = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
b = np.array([[30],[50],[70],[90]])

print('a')
print(a)
print()
print('b')
print(b)
print()
print('a + b - broadcasting to columns - b is repeated 2 more times so it is now 3 columns , same as a')
a + b

a
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]

b
[[30]
 [50]
 [70]
 [90]]

a + b - broadcasting to columns - b is repeated 2 more times so it is now 3 columns , same as a


array([[31, 31, 31],
       [52, 52, 52],
       [73, 73, 73],
       [94, 94, 94]])

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

a[1:3,1:3] +=5
a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3],
       [ 4, 10, 11],
       [ 7, 13, 14]])